embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
reg_weight: [0.0, 1e-05, 1e-04, 1e-03] #增加一个0.6，模态BPR损失的权重

n_mm_layers: 1
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1 #视觉模态邻接矩阵权重
dropout: [0.8,0.9] #原本是FREEDOM模型的剪枝率[0.8, 0.9]；修改使其成为DGSMR模型中的对比损失的超参

hyper_parameters: ["dropout", "reg_weight"]
