embedding_size: 64
feat_embed_dim: 64

n_layers: [1, 2]
dropout: [0.3, 0.5]
reg_weight: [0.1, 0.01,0.001]
cl_weight: 2.0

use_neg_sampling: False

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

norm_type: "sym"
sparse: True
lambda_coeff: 0.9
item_topk : 10
layers: 2
loss_ratio: 0.03